// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSDKI_CLeg5O79bxQe0SkU238BHVPmTUQ',
    appId: '1:67553841343:web:3f6b0871df393fdc10f60a',
    messagingSenderId: '67553841343',
    projectId: 'flutter-ecomm-7adcd',
    authDomain: 'flutter-ecomm-7adcd.firebaseapp.com',
    storageBucket: 'flutter-ecomm-7adcd.appspot.com',
    measurementId: 'G-Z4W1T982PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASZCvMBeAwH8GvcTmZCQlF78NldEsEtT8',
    appId: '1:67553841343:android:612d24939bc7065010f60a',
    messagingSenderId: '67553841343',
    projectId: 'flutter-ecomm-7adcd',
    storageBucket: 'flutter-ecomm-7adcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1_Fdie52gzR3GgMOHROltlX82GIrmfTA',
    appId: '1:67553841343:ios:f37d01a45d9caa3710f60a',
    messagingSenderId: '67553841343',
    projectId: 'flutter-ecomm-7adcd',
    storageBucket: 'flutter-ecomm-7adcd.appspot.com',
    iosClientId: '67553841343-et13en16lcr4tltm3fh72o68o8a95m8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.medusa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1_Fdie52gzR3GgMOHROltlX82GIrmfTA',
    appId: '1:67553841343:ios:f37d01a45d9caa3710f60a',
    messagingSenderId: '67553841343',
    projectId: 'flutter-ecomm-7adcd',
    storageBucket: 'flutter-ecomm-7adcd.appspot.com',
    iosClientId: '67553841343-et13en16lcr4tltm3fh72o68o8a95m8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.medusa',
  );
}
